language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - '7.1'
    - '7.2'

before_script:
    - flags="-o"
    - composer install $flags

script: make travis

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: mg-bot-api-client-php.pages
    keep_history: true
    on:
        branch: master